name: super_dns_client
description: A modern and lightweight Dart library for performing DNS-over-HTTPS (DoH) lookups. Supports multiple resolvers and easy integration for Flutter and server-side apps.
version: 0.3.6
homepage: https://github.com/dab246/super_dns_client
repository: https://github.com/dab246/super_dns_client
issue_tracker: https://github.com/dab246/super_dns_client/issues
topics:
  - dns
  - doh
  - network
  - http
  - resolver

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  super_raw: ^0.1.0
  super_dns: ^0.1.1
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  lints: ^5.0.0
  test: ^1.25.2

flutter:
  plugin:
    platforms:
      android:
        package: com.example.super_dns_client
        pluginClass: SuperDnsClientPlugin
      ios:
        pluginClass: SuperDnsClientPlugin
